const products = [
  {
    id: 1,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #1',
    price: 34.75,
    isNew: false,
    category: 'women',
  },
  {
    id: 2,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #2',
    price: 34.75,
    isNew: true,
    category: 'women',
  },
  {
    id: 3,
    img: '/assets/product-02.jpg',
    title: 'Random Name #3',
    price: 34.75,
    isNew: false,
    category: 'women',
  },
  {
    id: 4,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #4',
    price: 34.75,
    isNew: true,
    category: 'women',
  },
  {
    id: 5,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #5',
    price: 34.75,
    isNew: true,
    category: 'women',
  },
  {
    id: 6,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #6',
    price: 34.75,
    isNew: true,
    category: 'women',
  },
  {
    id: 7,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #1',
    price: 34.75,
    isNew: true,
    category: 'men',
  },
  {
    id: 8,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #2',
    price: 34.75,
    isNew: true,
    category: 'men',
  },
  {
    id: 9,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #3',
    price: 34.75,
    isNew: true,
    category: 'men',
  },
  {
    id: 10,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #4',
    price: 34.75,
    isNew: true,
    category: 'men',
  },
  {
    id: 11,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #5',
    price: 34.75,
    isNew: true,
    category: 'men',
  },
  {
    id: 12,
    img: '../../../assets/product-02.jpg',
    title: 'Random Name #6',
    price: 34.75,
    isNew: true,
    category: 'men',
  },
];

export default products;
