export const products = [
  {
    id: 1,
    name: 'Herschel supply',
    desc: 'Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 2,
    name: 'Herschel supply',
    desc: 'Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 3,
    name: 'Herschel supply',
    desc: 'Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 4,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 5,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 6,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 7,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 8,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 9,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 10,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 11,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 12,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 13,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 14,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 15,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 16,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 17,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 18,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 19,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 20,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 21,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 22,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 23,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 24,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 25,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 26,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 27,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 28,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
  {
    id: 29,
    name: 'Herschel supply',
    img: './assets/product-detail-01.jpg',
    thumbs: [
      './assets/product-detail-01.jpg',
      './assets/product-detail-02.jpg',
      './assets/product-detail-03.jpg',
    ],
    price: 35.31,
    isLiked: false,
  },
];
